SymEdit\Bundle\WidgetBundle\Model\Widget:
    type: entity
    table: widget
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 255
            unique: true
            nullable: false
        title:
            type: string
            length: 255
            nullable: true
        options:
            type: json_array
        visibility:
            type: integer
            nullable: false
            default: 0
        assoc:
            type: json_array
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        strategyName:
            type: string
            length: 255
            nullable: false
            column: strategy_name
        widgetOrder:
            type: integer
            nullable: false
            gedmo:
                - sortablePosition
    manyToOne:
        area:
            targetEntity: SymEdit\Bundle\WidgetBundle\Model\WidgetAreaInterface
            inversedBy: widgets
            gedmo:
                - sortableGroup
